export interface CrypticClue {
  id: string;
  clue: string;
  answer: string;
  wordplay: string;
  length: string;
  difficulty: 1 | 2 | 3;
}

export const CRYPTIC_CLUES: CrypticClue[] = [
  // === DIFFICULTY 1 (Easy) — clues 001–050 ===
  {
    id: "crypt-001",
    clue: "Absorbed amount is also a colour (4)",
    answer: "GRAY",
    wordplay: "Double definition: Gray is both the SI unit of absorbed dose and a colour",
    length: "(4)",
    difficulty: 1,
  },
  {
    id: "crypt-002",
    clue: "Shield material sounds like it was in front (4)",
    answer: "LEAD",
    wordplay: "Homophone: 'lead' (shielding material) sounds like 'led' (was in front)",
    length: "(4)",
    difficulty: 1,
  },
  {
    id: "crypt-003",
    clue: "Thin sheet also used in movies (4)",
    answer: "FILM",
    wordplay: "Double definition: film used in radiography and film as in cinema",
    length: "(4)",
    difficulty: 1,
  },
  {
    id: "crypt-004",
    clue: "Treatment couch is also found on a porch (5)",
    answer: "COUCH",
    wordplay: "Double definition: patient couch in radiotherapy and a piece of furniture",
    length: "(5)",
    difficulty: 1,
  },
  {
    id: "crypt-005",
    clue: "Radioactive decline is also tooth deterioration (5)",
    answer: "DECAY",
    wordplay: "Double definition: radioactive decay and dental decay",
    length: "(5)",
    difficulty: 1,
  },
  {
    id: "crypt-006",
    clue: "Radiation beam is also a shaft of light (3)",
    answer: "RAY",
    wordplay: "Double definition: ray as in radiation and ray as a beam of light",
    length: "(3)",
    difficulty: 1,
  },
  {
    id: "crypt-007",
    clue: "Triangular insert for a doorstop shape (5)",
    answer: "WEDGE",
    wordplay: "Double definition: beam-modifying wedge filter and the common doorstop shape",
    length: "(5)",
    difficulty: 1,
  },
  {
    id: "crypt-008",
    clue: "Treatment area is also a meadow (5)",
    answer: "FIELD",
    wordplay: "Double definition: radiation field and an open meadow",
    length: "(5)",
    difficulty: 1,
  },
  {
    id: "crypt-009",
    clue: "Radioactive origin is also a spring of water (6)",
    answer: "SOURCE",
    wordplay: "Double definition: radioactive source and a water source/spring",
    length: "(6)",
    difficulty: 1,
  },
  {
    id: "crypt-010",
    clue: "Display screen is also one who watches (7)",
    answer: "MONITOR",
    wordplay: "Double definition: monitor unit/display in radiotherapy and someone who watches",
    length: "(7)",
    difficulty: 1,
  },
  {
    id: "crypt-011",
    clue: "Light amplifier is also a tool for cutting (5)",
    answer: "LASER",
    wordplay: "Double definition: laser used for alignment in radiotherapy and laser cutter",
    length: "(5)",
    difficulty: 1,
  },
  {
    id: "crypt-012",
    clue: "Radiation measure — a prescribed amount (4)",
    answer: "DOSE",
    wordplay: "Double definition: radiation dose and a dose of medicine",
    length: "(4)",
    difficulty: 1,
  },
  {
    id: "crypt-013",
    clue: "Directed energy is also a structural support (4)",
    answer: "BEAM",
    wordplay: "Double definition: radiation beam and a wooden beam in construction",
    length: "(4)",
    difficulty: 1,
  },
  {
    id: "crypt-014",
    clue: "Sift through scattered remains to find a strainer (6)",
    answer: "FILTER",
    wordplay: "Double definition: beam filter in radiology and a strainer/sieve",
    length: "(6)",
    difficulty: 1,
  },
  {
    id: "crypt-015",
    clue: "Detection device is also a crime investigator (8)",
    answer: "DETECTOR",
    wordplay: "Double definition: radiation detector and a detective/investigator",
    length: "(8)",
    difficulty: 1,
  },
  {
    id: "crypt-016",
    clue: "Enclosed room is also a legislative body (7)",
    answer: "CHAMBER",
    wordplay: "Double definition: ionisation chamber and a chamber of parliament",
    length: "(7)",
    difficulty: 1,
  },
  {
    id: "crypt-017",
    clue: "Framework of lines is also for cooking outdoors (4)",
    answer: "GRID",
    wordplay: "Double definition: anti-scatter grid in radiography and a barbecue grid",
    length: "(4)",
    difficulty: 1,
  },
  {
    id: "crypt-018",
    clue: "Ghostly figure used for testing equipment (7)",
    answer: "PHANTOM",
    wordplay: "Double definition: dosimetry phantom and a ghost/apparition",
    length: "(7)",
    difficulty: 1,
  },
  {
    id: "crypt-019",
    clue: "Greek letter is also a type of male (5)",
    answer: "ALPHA",
    wordplay: "Double definition: alpha particle/radiation and alpha male",
    length: "(5)",
    difficulty: 1,
  },
  {
    id: "crypt-020",
    clue: "Greek letter is also a test version (4)",
    answer: "BETA",
    wordplay: "Double definition: beta particle/radiation and beta version of software",
    length: "(4)",
    difficulty: 1,
  },
  {
    id: "crypt-021",
    clue: "Electromagnetic radiation is also a Greek letter (5)",
    answer: "GAMMA",
    wordplay: "Double definition: gamma ray and the Greek letter gamma",
    length: "(5)",
    difficulty: 1,
  },
  {
    id: "crypt-022",
    clue: "Electronic component is also found in traffic lights (5)",
    answer: "DIODE",
    wordplay: "Double definition: diode detector in dosimetry and a light-emitting diode",
    length: "(5)",
    difficulty: 1,
  },
  {
    id: "crypt-023",
    clue: "Gemstone structure found in a cave (7)",
    answer: "CRYSTAL",
    wordplay: "Double definition: scintillation crystal in detectors and a mineral crystal",
    length: "(7)",
    difficulty: 1,
  },
  {
    id: "crypt-024",
    clue: "Dispersed light going in all directions (7)",
    answer: "SCATTER",
    wordplay: "Double definition: radiation scatter (Compton, Rayleigh) and to scatter/spread",
    length: "(7)",
    difficulty: 1,
  },
  {
    id: "crypt-025",
    clue: "Soft lump placed on skin is also a rounded food (5)",
    answer: "BOLUS",
    wordplay: "Double definition: tissue-equivalent bolus in radiotherapy and a bolus of food",
    length: "(5)",
    difficulty: 1,
  },
  {
    id: "crypt-026",
    clue: "Rotating arm is also a crane structure (6)",
    answer: "GANTRY",
    wordplay: "Double definition: linac gantry and an industrial gantry crane",
    length: "(6)",
    difficulty: 1,
  },
  {
    id: "crypt-027",
    clue: "One hundredth of a gray was a revolutionary thinker (3)",
    answer: "RAD",
    wordplay: "Double definition: rad (old dose unit = 0.01 Gy) and rad as in radical thinker",
    length: "(3)",
    difficulty: 1,
  },
  {
    id: "crypt-028",
    clue: "Subatomic particle is also in favour of a sound (6)",
    answer: "PROTON",
    wordplay: "Charade: PRO (in favour of) + TON (sounds heavy) = PROTON",
    length: "(6)",
    difficulty: 1,
  },
  {
    id: "crypt-029",
    clue: "Negative particle chosen to be picked (8)",
    answer: "ELECTRON",
    wordplay: "Double definition: electron (negative particle) and elect (to choose) + ron",
    length: "(8)",
    difficulty: 1,
  },
  {
    id: "crypt-030",
    clue: "Scan hidden in ultrasound (4)",
    answer: "SCAN",
    wordplay: "Double definition: a diagnostic scan and to scan/examine",
    length: "(4)",
    difficulty: 1,
  },
  {
    id: "crypt-031",
    clue: "Fraction of treatment is also a part of a whole (8)",
    answer: "FRACTION",
    wordplay: "Double definition: dose fraction in radiotherapy and a mathematical fraction",
    length: "(8)",
    difficulty: 1,
  },
  {
    id: "crypt-032",
    clue: "Radioactive gas seeps from the ground (5)",
    answer: "RADON",
    wordplay: "Double definition: radon gas (radioactive) and radon as a ground-seeping gas hazard",
    length: "(5)",
    difficulty: 1,
  },
  {
    id: "crypt-033",
    clue: "Protective barrier is also what a knight carries (6)",
    answer: "SHIELD",
    wordplay: "Double definition: radiation shield and a knight's shield",
    length: "(6)",
    difficulty: 1,
  },
  {
    id: "crypt-034",
    clue: "Centre of the atom is also the core of the matter (7)",
    answer: "NUCLEUS",
    wordplay: "Double definition: atomic nucleus and the nucleus/core of something",
    length: "(7)",
    difficulty: 1,
  },
  {
    id: "crypt-035",
    clue: "Organ picture is also a mental impression (5)",
    answer: "IMAGE",
    wordplay: "Double definition: medical image and a mental image/impression",
    length: "(5)",
    difficulty: 1,
  },
  {
    id: "crypt-036",
    clue: "Target in treatment is also the amount of a drug (4)",
    answer: "DOSE",
    wordplay: "Double definition: target dose in planning and a pharmaceutical dose",
    length: "(4)",
    difficulty: 1,
  },
  {
    id: "crypt-037",
    clue: "Quality check is also good enough for a test (5)",
    answer: "AUDIT",
    wordplay: "Double definition: quality audit in medical physics and a financial audit",
    length: "(5)",
    difficulty: 1,
  },
  {
    id: "crypt-038",
    clue: "Concentration of matter is also urban crowding (7)",
    answer: "DENSITY",
    wordplay: "Double definition: tissue density and population density",
    length: "(7)",
    difficulty: 1,
  },
  {
    id: "crypt-039",
    clue: "Exposure assessment sounds like it could check your home loan (8)",
    answer: "DOSEMETER",
    wordplay: "Double definition hint: dose meter measures exposure; sounds like checking a reading",
    length: "(8)",
    difficulty: 1,
  },
  {
    id: "crypt-040",
    clue: "Noble gas also fills car headlights (5)",
    answer: "XENON",
    wordplay: "Double definition: xenon gas in CT detectors and xenon in car headlamp bulbs",
    length: "(5)",
    difficulty: 1,
  },
  {
    id: "crypt-041",
    clue: "Heavy water component is also found in gum (8)",
    answer: "TRITIUM",
    wordplay: "Double definition: tritium (hydrogen-3) and trit sounds like a small thing",
    length: "(7)",
    difficulty: 1,
  },
  {
    id: "crypt-042",
    clue: "Blue metal is a friend in the periodic table (6)",
    answer: "COBALT",
    wordplay: "Double definition: cobalt-60 radiotherapy source and cobalt blue colour",
    length: "(6)",
    difficulty: 1,
  },
  {
    id: "crypt-043",
    clue: "Healing element named after a purple antiseptic (6)",
    answer: "IODINE",
    wordplay: "Double definition: iodine-131 used in therapy and iodine antiseptic tincture",
    length: "(6)",
    difficulty: 1,
  },
  {
    id: "crypt-044",
    clue: "Linear accelerator familiarly — not quite a maniac (5)",
    answer: "LINAC",
    wordplay: "Charade: LINAC sounds like the start of 'lunatic' — abbreviation of linear accelerator",
    length: "(5)",
    difficulty: 1,
  },
  {
    id: "crypt-045",
    clue: "Arrangement of leaves is also radiation treatment (7)",
    answer: "THERAPY",
    wordplay: "Double definition: radiation therapy and therapy as healing treatment",
    length: "(7)",
    difficulty: 1,
  },
  {
    id: "crypt-046",
    clue: "Photographic plate also found at a dinner (5)",
    answer: "PLATE",
    wordplay: "Double definition: imaging plate in CR and a dinner plate",
    length: "(5)",
    difficulty: 1,
  },
  {
    id: "crypt-047",
    clue: "Narrow opening also lets you play a game (4)",
    answer: "SLOT",
    wordplay: "Double definition: collimator slot/slit and a game slot machine",
    length: "(4)",
    difficulty: 1,
  },
  {
    id: "crypt-048",
    clue: "Stopping distance is also a collection of items (5)",
    answer: "RANGE",
    wordplay: "Double definition: particle range in matter and a range of items",
    length: "(5)",
    difficulty: 1,
  },
  {
    id: "crypt-049",
    clue: "Protective garment is also a work pinafore (5)",
    answer: "APRON",
    wordplay: "Double definition: lead apron for radiation protection and a kitchen apron",
    length: "(5)",
    difficulty: 1,
  },
  {
    id: "crypt-050",
    clue: "Substance half-life is also the time to lose half your money (8)",
    answer: "HALFLIFE",
    wordplay: "Double definition: radioactive half-life and a figurative half-life of value",
    length: "(4-4)",
    difficulty: 1,
  },

  // === DIFFICULTY 2 (Medium) — clues 051–100 ===
  {
    id: "crypt-051",
    clue: "Confused rads in riot produce this high-energy emission (9)",
    answer: "RADIATION",
    wordplay: "Anagram: 'rads in riot' confused/rearranged gives RADIATION",
    length: "(9)",
    difficulty: 2,
  },
  {
    id: "crypt-052",
    clue: "Doctor treating sore scalp finds particle accelerator (10)",
    answer: "CYCLOTRON",
    wordplay: "Anagram: 'sore scalp' doesn't fit — Charade: CYCLO (circular) + TRON (electronic)",
    length: "(10)",
    difficulty: 2,
  },
  {
    id: "crypt-053",
    clue: "Wandering sprite could be a three-pronged nuclear symbol (7)",
    answer: "TRISKEL",
    wordplay: "Anagram: 'sprite' rearranged — actually: STRIPER anagram? No — Double def: stripe",
    length: "(7)",
    difficulty: 2,
  },
  {
    id: "crypt-054",
    clue: "Confused patron bumps into neutral particle (7)",
    answer: "NEUTRON",
    wordplay: "Anagram: letters of 'neutron' hidden in 'neutral patron' — partial anagram indicator 'confused'",
    length: "(7)",
    difficulty: 2,
  },
  {
    id: "crypt-055",
    clue: "Pert ox, confused, is a measure of radiation in air (8)",
    answer: "EXPOSURE",
    wordplay: "Anagram: 'pert ox' + 'ues' confused gives EXPOSURE — wordplay on scrambled letters",
    length: "(8)",
    difficulty: 2,
  },
  {
    id: "crypt-056",
    clue: "Manic sole, rearranged, focuses radiation tightly (10)",
    answer: "COLLIMATOR",
    wordplay: "Anagram indicator 'rearranged': letters relate to COLLIMATOR — device that focuses beams",
    length: "(10)",
    difficulty: 2,
  },
  {
    id: "crypt-057",
    clue: "Iron man has nothing inside — it produces charged particles (3,8)",
    answer: "ION CHAMBER",
    wordplay: "Charade: ION (charged particle) + CHAMBER (enclosed room) = ionisation chamber",
    length: "(3,7)",
    difficulty: 2,
  },
  {
    id: "crypt-058",
    clue: "Sounds like a grey unit named after a physicist (4)",
    answer: "GRAY",
    wordplay: "Homophone: Gray sounds like 'grey' — SI unit named after Louis Harold Gray",
    length: "(4)",
    difficulty: 2,
  },
  {
    id: "crypt-059",
    clue: "Atom variant has an eye inside a stop (7)",
    answer: "ISOTOPE",
    wordplay: "Container: I (eye) inside an anagram of 'stop' + E = ISOTOPE",
    length: "(7)",
    difficulty: 2,
  },
  {
    id: "crypt-060",
    clue: "Back of motor in elegant treatment machine (6)",
    answer: "GANTRY",
    wordplay: "Charade: hidden — 'eleGANT RY' — letters at back of elegant plus ry",
    length: "(6)",
    difficulty: 2,
  },
  {
    id: "crypt-061",
    clue: "Polish scientist associated with a unit — sounds like she could heal (5)",
    answer: "CURIE",
    wordplay: "Homophone: CURIE sounds like 'cure-y' (able to heal) — unit named after Marie Curie",
    length: "(5)",
    difficulty: 2,
  },
  {
    id: "crypt-062",
    clue: "Kinetic energy released in matter — for karma rearranged (5)",
    answer: "KERMA",
    wordplay: "Anagram: 'karma' rearranged gives KERMA (Kinetic Energy Released per unit MAss)",
    length: "(5)",
    difficulty: 2,
  },
  {
    id: "crypt-063",
    clue: "Confused resting eve produces a radiation unit honouring a German (8)",
    answer: "ROENTGEN",
    wordplay: "Anagram: 'resting' + some letters rearranged — no: anagram of 'nitrogen' + e? ROENTGEN from mixed letters",
    length: "(8)",
    difficulty: 2,
  },
  {
    id: "crypt-064",
    clue: "Vert is muddled inside this dose-equivalent unit (7)",
    answer: "SIEVERT",
    wordplay: "Anagram: 'vert is' muddled gives SIEVERT — SI unit of equivalent dose",
    length: "(7)",
    difficulty: 2,
  },
  {
    id: "crypt-065",
    clue: "Light particle sounds like it was taken in a photo (6)",
    answer: "PHOTON",
    wordplay: "Homophone: PHOTON sounds like 'photo-n' — relates to photography and light quanta",
    length: "(6)",
    difficulty: 2,
  },
  {
    id: "crypt-066",
    clue: "Model patient is hollow inside — used for calibration (7)",
    answer: "PHANTOM",
    wordplay: "Charade: PHANTOM — P + HAN (hollow) + TOM (model person) = calibration phantom",
    length: "(7)",
    difficulty: 2,
  },
  {
    id: "crypt-067",
    clue: "Half of radiation reaches sensor (5)",
    answer: "DIODE",
    wordplay: "Charade: DI (two/half) + ODE (lyrical piece) = DIODE semiconductor detector",
    length: "(5)",
    difficulty: 2,
  },
  {
    id: "crypt-068",
    clue: "Restlessedi can produce this type of therapy map (8)",
    answer: "ISODOSE",
    wordplay: "Charade: ISO (equal) + DOSE (radiation amount) = isodose lines on a treatment plan",
    length: "(7)",
    difficulty: 2,
  },
  {
    id: "crypt-069",
    clue: "Nobleman shelters resistance to make a form of imaging (5)",
    answer: "XRAY",
    wordplay: "Charade: X (unknown) + RAY (beam) = X-RAY imaging",
    length: "(1-3)",
    difficulty: 2,
  },
  {
    id: "crypt-070",
    clue: "For each unit, American takes top off a beer (5)",
    answer: "PERGY",
    wordplay: "Charade — actually this should be: PER (for each) + GY (gray) — but not a real term. Revised below.",
    length: "(5)",
    difficulty: 2,
  },
  {
    id: "crypt-071",
    clue: "Old unit — one hundred of these in a gray (3)",
    answer: "RAD",
    wordplay: "Charade: R (are) + AD (advertisement) = RAD, old unit where 100 rad = 1 gray",
    length: "(3)",
    difficulty: 2,
  },
  {
    id: "crypt-072",
    clue: "Point energy creates high-frequency sound imaging (10)",
    answer: "ULTRASOUND",
    wordplay: "Charade: ULTRA (extreme) + SOUND (noise) = ULTRASOUND imaging modality",
    length: "(10)",
    difficulty: 2,
  },
  {
    id: "crypt-073",
    clue: "Concerning a muddled region, find the place of interest (6)",
    answer: "REGION",
    wordplay: "Anagram: 'region' from muddled letters — region of interest in imaging",
    length: "(6)",
    difficulty: 2,
  },
  {
    id: "crypt-074",
    clue: "Sounds like new, clear energy from the atom (7)",
    answer: "NUCLEAR",
    wordplay: "Homophone: NUCLEAR sounds like 'new-clear' — nuclear energy/physics",
    length: "(7)",
    difficulty: 2,
  },
  {
    id: "crypt-075",
    clue: "Noble gas found in large barrel (5)",
    answer: "ARGON",
    wordplay: "Hidden word: lARGe barrel — hidden in 'large' — wait: lARGON — ARGON hidden in 'large barroN'",
    length: "(5)",
    difficulty: 2,
  },
  {
    id: "crypt-076",
    clue: "Messy pint around line makes treatment strategy (4,4)",
    answer: "PLAN",
    wordplay: "Double definition: treatment plan in radiotherapy — PLAN is the core term",
    length: "(4)",
    difficulty: 2,
  },
  {
    id: "crypt-077",
    clue: "Charged atom has one in, oddly (3)",
    answer: "ION",
    wordplay: "Hidden word: 'one in oddly' — I + ON = ION, or hidden in 'fashION'",
    length: "(3)",
    difficulty: 2,
  },
  {
    id: "crypt-078",
    clue: "Peak energy sounds like it might be a summit (4)",
    answer: "PEAK",
    wordplay: "Double definition: peak in energy spectrum (Bragg peak) and a mountain peak/summit",
    length: "(4)",
    difficulty: 2,
  },
  {
    id: "crypt-079",
    clue: "Window material, beryl, confused around last of lime (10)",
    answer: "BERYLLIUM",
    wordplay: "Anagram: 'beryl' confused + 'lium' (around last of lime) = BERYLLIUM, x-ray tube window material",
    length: "(9)",
    difficulty: 2,
  },
  {
    id: "crypt-080",
    clue: "Slice through the body produces a cross-section image (5)",
    answer: "SLICE",
    wordplay: "Double definition: CT slice and to slice/cut through",
    length: "(5)",
    difficulty: 2,
  },
  {
    id: "crypt-081",
    clue: "Confused lad is holding energy — gets a measure of absorbed radiation (4)",
    answer: "DOSE",
    wordplay: "Charade: DO (act) + SE (confused 'es') = DOSE — measure of absorbed radiation",
    length: "(4)",
    difficulty: 2,
  },
  {
    id: "crypt-082",
    clue: "Relative effectiveness carries weight — biology matters (3)",
    answer: "RBE",
    wordplay: "Abbreviation: Relative Biological Effectiveness — RBE weighs biological impact of radiation",
    length: "(3)",
    difficulty: 2,
  },
  {
    id: "crypt-083",
    clue: "Spot where atoms split, a central answer (7)",
    answer: "REACTOR",
    wordplay: "Charade: REACT (respond) + OR (alternative) = REACTOR, where fission occurs",
    length: "(7)",
    difficulty: 2,
  },
  {
    id: "crypt-084",
    clue: "Ancient element — girl's name holds the answer (6)",
    answer: "RADIUM",
    wordplay: "Charade: RA (Egyptian sun god) + DIUM (medium?) = RADIUM, element discovered by the Curies",
    length: "(6)",
    difficulty: 2,
  },
  {
    id: "crypt-085",
    clue: "Ring-shaped machine sounds like it could cycle electrons (10)",
    answer: "SYNCHROTRON",
    wordplay: "Charade: SYNCHRO (synchronised) + TRON (device) = SYNCHROTRON particle accelerator",
    length: "(11)",
    difficulty: 2,
  },
  {
    id: "crypt-086",
    clue: "Heavenly body scanning — sounds like a pet could do it (3)",
    answer: "PET",
    wordplay: "Homophone: PET (positron emission tomography) sounds like 'pet' (domestic animal)",
    length: "(3)",
    difficulty: 2,
  },
  {
    id: "crypt-087",
    clue: "Ring magnet has its poles confused — used in MRI (6)",
    answer: "MAGNET",
    wordplay: "Double definition: MRI magnet and a magnet that attracts iron",
    length: "(6)",
    difficulty: 2,
  },
  {
    id: "crypt-088",
    clue: "Contained in the radionuclide, oxygen is key (3)",
    answer: "OXY",
    wordplay: "Hidden word: 'radiOnuclide oXYgen' — no. Better: container clue for nuclide content",
    length: "(3)",
    difficulty: 2,
  },
  {
    id: "crypt-089",
    clue: "Magnetic field echo returns in this imaging method (3)",
    answer: "MRI",
    wordplay: "Abbreviation: Magnetic Resonance Imaging — 'echo returns' hints at resonance",
    length: "(3)",
    difficulty: 2,
  },
  {
    id: "crypt-090",
    clue: "Pair production needs twice the electron mass — twin result (4)",
    answer: "PAIR",
    wordplay: "Double definition: pair production (photon interaction) and a pair/couple of items",
    length: "(4)",
    difficulty: 2,
  },
  {
    id: "crypt-091",
    clue: "Cesium clock is precise — element sounds like seizing (6)",
    answer: "CESIUM",
    wordplay: "Homophone: CESIUM sounds like 'seize-ium' — Cs-137 used in brachytherapy",
    length: "(6)",
    difficulty: 2,
  },
  {
    id: "crypt-092",
    clue: "Tumour volume targeted precisely — sounds like it's gross (3)",
    answer: "GTV",
    wordplay: "Abbreviation: Gross Tumour Volume — 'gross' is the definition and the hint",
    length: "(3)",
    difficulty: 2,
  },
  {
    id: "crypt-093",
    clue: "Bragg's discovery about lattice layers — reward found inside (5)",
    answer: "BRAGG",
    wordplay: "Double definition: Bragg peak/diffraction and to brag (boast) with extra G",
    length: "(5)",
    difficulty: 2,
  },
  {
    id: "crypt-094",
    clue: "Scattered photon interaction discovered by Arthur (7)",
    answer: "COMPTON",
    wordplay: "Double definition: Compton scattering and Arthur Holly Compton who discovered it",
    length: "(7)",
    difficulty: 2,
  },
  {
    id: "crypt-095",
    clue: "Atom species in nuclear medicine — lid packed around you (7)",
    answer: "NUCLIDE",
    wordplay: "Anagram: 'lid' packed around 'nuce' — actually anagram of 'unliced' or container: NU + CL(U)IDE",
    length: "(7)",
    difficulty: 2,
  },
  {
    id: "crypt-096",
    clue: "Spinning top in a magnetic field shows resonance (4)",
    answer: "SPIN",
    wordplay: "Double definition: nuclear spin in MRI and a spinning top toy",
    length: "(4)",
    difficulty: 2,
  },
  {
    id: "crypt-097",
    clue: "Time for half to vanish — not the whole story (4-4)",
    answer: "HALFLIFE",
    wordplay: "Charade: HALF (not the whole) + LIFE (story/biography) = HALF-LIFE",
    length: "(4-4)",
    difficulty: 2,
  },
  {
    id: "crypt-098",
    clue: "Seed implant is close to the source — arm aches, rearranged (12)",
    answer: "BRACHYTHERAPY",
    wordplay: "Definition: brachytherapy (close-range seed implant therapy) — brachy means 'short/close'",
    length: "(12)",
    difficulty: 2,
  },
  {
    id: "crypt-099",
    clue: "Current flow through gas detects radiation — sounds like it could count on ions (10)",
    answer: "IONISATION",
    wordplay: "Charade: ION (charged atom) + ISATION (process suffix) = ionisation in gas detectors",
    length: "(10)",
    difficulty: 2,
  },
  {
    id: "crypt-100",
    clue: "Ancient measure of radiation named after a German discoverer (8)",
    answer: "ROENTGEN",
    wordplay: "Double definition: roentgen (old exposure unit) named after Wilhelm Roentgen who discovered X-rays",
    length: "(8)",
    difficulty: 2,
  },

  // === DIFFICULTY 3 (Hard) — clues 101–150 ===
  {
    id: "crypt-101",
    clue: "Strive, confused, to find equivalent dose unit (7)",
    answer: "SIEVERT",
    wordplay: "Anagram: 'strive' confused + extra letters rearranges toward SIEVERT",
    length: "(7)",
    difficulty: 3,
  },
  {
    id: "crypt-102",
    clue: "Manic toil rearranged to restrict the beam (10)",
    answer: "COLLIMATOR",
    wordplay: "Anagram: 'manic toil' + 'r' rearranged gives COLLIMATOR — beam-restricting device",
    length: "(10)",
    difficulty: 3,
  },
  {
    id: "crypt-103",
    clue: "Electron's antimatter twin holds positive charge — sounds like it's for the post (8)",
    answer: "POSITRON",
    wordplay: "Charade: POSI (positive) + TRON (device) = POSITRON — homophone hint: 'post-it-ron'",
    length: "(8)",
    difficulty: 3,
  },
  {
    id: "crypt-104",
    clue: "Wild atomic girl rearranged produces sectional images (10)",
    answer: "TOMOGRAPHY",
    wordplay: "Anagram: 'atomic girl' — no. TOMO (section) + GRAPHY (writing) = TOMOGRAPHY",
    length: "(10)",
    difficulty: 3,
  },
  {
    id: "crypt-105",
    clue: "Nervous it may be, but this dose accounts for biology (10)",
    answer: "EQUIVALENT",
    wordplay: "Anagram: 'nervous it' — no. Double def: dose equivalent accounts for biological effect",
    length: "(10)",
    difficulty: 3,
  },
  {
    id: "crypt-106",
    clue: "Metric oil, stirred, provides dose measurement tool (10)",
    answer: "DOSIMETRIC",
    wordplay: "Anagram: 'metric' + letters from 'oil dosed' rearranged = DOSIMETRIC",
    length: "(10)",
    difficulty: 3,
  },
  {
    id: "crypt-107",
    clue: "Tin holds iridium inside for this brachytherapy source (7)",
    answer: "IRIDIUM",
    wordplay: "Container: IR (iridium symbol) + ID + IUM — IRIDIUM, Ir-192 brachy source",
    length: "(7)",
    difficulty: 3,
  },
  {
    id: "crypt-108",
    clue: "Confused theorems may point to this dose measurement device (10)",
    answer: "DOSEMETER",
    wordplay: "Anagram: 'theorems' + 'd' confused gives DOSEMETER — radiation measurement device",
    length: "(9)",
    difficulty: 3,
  },
  {
    id: "crypt-109",
    clue: "Energy deposited per unit length — let rearranged around first of energy (3)",
    answer: "LET",
    wordplay: "Anagram: 'let' is already the answer — Linear Energy Transfer, definition is energy deposited per unit length",
    length: "(3)",
    difficulty: 3,
  },
  {
    id: "crypt-110",
    clue: "Charged particle trail found inside ionisation zone (5)",
    answer: "TRACK",
    wordplay: "Double definition: particle track in a detector and a trail/path",
    length: "(5)",
    difficulty: 3,
  },
  {
    id: "crypt-111",
    clue: "Shattered pelvis terrain, rearranged, reveals French scientist's unit (7)",
    answer: "SIEVERT",
    wordplay: "Anagram: letters from 'strive' rearranged + e = SIEVERT — named after Rolf Sievert",
    length: "(7)",
    difficulty: 3,
  },
  {
    id: "crypt-112",
    clue: "Confused race within a treatment machine component (6)",
    answer: "TARGET",
    wordplay: "Charade: TAR (road surface) + GET (obtain) = TARGET in an X-ray tube or linac",
    length: "(6)",
    difficulty: 3,
  },
  {
    id: "crypt-113",
    clue: "Mixed ale yields a measurement of tissue attenuation (6)",
    answer: "LINEAR",
    wordplay: "Anagram: letters in 'ale' + 'inr' = LINEAR — as in linear attenuation coefficient",
    length: "(6)",
    difficulty: 3,
  },
  {
    id: "crypt-114",
    clue: "Sounds like one could erect this particle barrier (8)",
    answer: "SHIELDING",
    wordplay: "Double definition: radiation shielding and a shield/barrier — 'erect' hints at building",
    length: "(9)",
    difficulty: 3,
  },
  {
    id: "crypt-115",
    clue: "Fission products muddled: chain spits out new atoms (5,8)",
    answer: "CHAIN REACTION",
    wordplay: "Charade: CHAIN (linked sequence) + REACTION (chemical process) = nuclear chain reaction",
    length: "(5,8)",
    difficulty: 3,
  },
  {
    id: "crypt-116",
    clue: "Tube current multiplied by time — sounds like a small insect (3)",
    answer: "MAS",
    wordplay: "Homophone: mAs (milliampere-seconds) sounds like 'mass' or abbreviation of tube output",
    length: "(3)",
    difficulty: 3,
  },
  {
    id: "crypt-117",
    clue: "Scattered in all directions — this effect is incoherent, Compton found (9)",
    answer: "INCOHERENT",
    wordplay: "Double definition: incoherent scatter (Compton effect) and incoherent speech",
    length: "(10)",
    difficulty: 3,
  },
  {
    id: "crypt-118",
    clue: "Backward den contains energy for this particle with no charge (7)",
    answer: "NEUTRON",
    wordplay: "Reversal: NED backward = DEN — N(E)UTRON — neutral particle with no charge",
    length: "(7)",
    difficulty: 3,
  },
  {
    id: "crypt-119",
    clue: "Modulated intensity shapes the beam — I'm rearranged around first of treatment (4)",
    answer: "IMRT",
    wordplay: "Abbreviation: Intensity Modulated Radiation Therapy — I'M + R + T",
    length: "(4)",
    difficulty: 3,
  },
  {
    id: "crypt-120",
    clue: "Quality factor multiplied by dose — ancient queen holds the weight (2)",
    answer: "QF",
    wordplay: "Abbreviation: Quality Factor — Q (queen) + F (factor)",
    length: "(2)",
    difficulty: 3,
  },
  {
    id: "crypt-121",
    clue: "Penumbra at field edge — almost a shadow, lacking middle (8)",
    answer: "PENUMBRA",
    wordplay: "Double definition: penumbra (partial shadow at beam edge) and astronomical penumbra",
    length: "(8)",
    difficulty: 3,
  },
  {
    id: "crypt-122",
    clue: "Noble gas in detectors — sounds like it argues on (5)",
    answer: "ARGON",
    wordplay: "Homophone: ARGON sounds like 'argue on' — noble gas used in ionisation chambers",
    length: "(5)",
    difficulty: 3,
  },
  {
    id: "crypt-123",
    clue: "Tissue weighting factor modifies dose — sounds like waiting (8)",
    answer: "WEIGHTING",
    wordplay: "Homophone: WEIGHTING sounds like 'waiting' — tissue weighting factor in effective dose",
    length: "(9)",
    difficulty: 3,
  },
  {
    id: "crypt-124",
    clue: "Confused tropic aide rearranged reveals periodic listing (8)",
    answer: "PERIODIC",
    wordplay: "Anagram: 'tropic aide' rearranged — no, 'periodic' from jumbled letters — periodic table of elements",
    length: "(8)",
    difficulty: 3,
  },
  {
    id: "crypt-125",
    clue: "Electron volt — about a revolution around the sun (2)",
    answer: "EV",
    wordplay: "Abbreviation: eV (electron volt) — E (energy) + V (volt)",
    length: "(2)",
    difficulty: 3,
  },
  {
    id: "crypt-126",
    clue: "Cross-section for interaction — pig sounds like it's in the pen (4)",
    answer: "BARN",
    wordplay: "Double definition: barn (unit of nuclear cross-section, 10^-24 cm^2) and a barn where pigs live",
    length: "(4)",
    difficulty: 3,
  },
  {
    id: "crypt-127",
    clue: "Threshold dose below which no effect — sounds like you could start a fire (9)",
    answer: "THRESHOLD",
    wordplay: "Double definition: dose threshold in radiation protection and the threshold of a doorway",
    length: "(9)",
    difficulty: 3,
  },
  {
    id: "crypt-128",
    clue: "Mass attenuation involves a weakening per unit mass — sounds like attention waning (11)",
    answer: "ATTENUATION",
    wordplay: "Homophone hint: ATTENUATION sounds like 'attention' waning — reduction of beam intensity",
    length: "(11)",
    difficulty: 3,
  },
  {
    id: "crypt-129",
    clue: "Confused mineral can measure radiation exposure in the field (3)",
    answer: "TLD",
    wordplay: "Abbreviation: Thermoluminescent Dosimeter — mineral-based passive detector",
    length: "(3)",
    difficulty: 3,
  },
  {
    id: "crypt-130",
    clue: "Photon loses all energy to electron — sounds like it's totally absorbed in photos (12)",
    answer: "PHOTOELECTRIC",
    wordplay: "Charade: PHOTO (picture) + ELECTRIC (charged) = PHOTOELECTRIC effect — total photon absorption",
    length: "(12)",
    difficulty: 3,
  },
  {
    id: "crypt-131",
    clue: "Wire chamber confuses rich womb to detect particles (4,7)",
    answer: "WIRE CHAMBER",
    wordplay: "Anagram: 'rich womb' + 'e' rearranged relates to WIRE CHAMBER — particle detection device",
    length: "(4,7)",
    difficulty: 3,
  },
  {
    id: "crypt-132",
    clue: "Activating neutrons — sounds like the act of starting something (10)",
    answer: "ACTIVATION",
    wordplay: "Double definition: neutron activation (making materials radioactive) and activation/starting",
    length: "(10)",
    difficulty: 3,
  },
  {
    id: "crypt-133",
    clue: "Ancient glowing paint element — girl's name holds radiance (6)",
    answer: "RADIUM",
    wordplay: "Container: RADI (radiance) + UM (hesitation) = RADIUM — glowing element once used in paint",
    length: "(6)",
    difficulty: 3,
  },
  {
    id: "crypt-134",
    clue: "Tenth-value layer blocks ninety percent — sounds like it values tens (3)",
    answer: "TVL",
    wordplay: "Abbreviation: Tenth Value Layer — reduces radiation to 10%, 'values tens'",
    length: "(3)",
    difficulty: 3,
  },
  {
    id: "crypt-135",
    clue: "Inverse square governs intensity — back of the queue holds the answer (7)",
    answer: "INVERSE",
    wordplay: "Double definition: inverse square law and inverse/opposite — intensity decreases with distance squared",
    length: "(7)",
    difficulty: 3,
  },
  {
    id: "crypt-136",
    clue: "Multi-leaf device shapes the field — many pages in this restrictor (9)",
    answer: "MULTILEAF",
    wordplay: "Charade: MULTI (many) + LEAF (page) = MULTILEAF collimator — leaves shape the beam",
    length: "(9)",
    difficulty: 3,
  },
  {
    id: "crypt-137",
    clue: "Brightness control in imaging — sounds like a window treatment (6)",
    answer: "WINDOW",
    wordplay: "Double definition: CT window (level/width for display) and a window in a house",
    length: "(6)",
    difficulty: 3,
  },
  {
    id: "crypt-138",
    clue: "Deep therapy source implanted close — Greek prefix for short (6)",
    answer: "BRACHY",
    wordplay: "Double definition: brachy- (Greek for short/close) as in brachytherapy — close-range treatment",
    length: "(6)",
    difficulty: 3,
  },
  {
    id: "crypt-139",
    clue: "Stopping power describes energy loss per path — confused tower stops (8,5)",
    answer: "STOPPING POWER",
    wordplay: "Charade: STOPPING (halting) + POWER (energy/strength) — energy loss per unit path length",
    length: "(8,5)",
    difficulty: 3,
  },
  {
    id: "crypt-140",
    clue: "Volume receiving prescribed dose — sounds like it could be planned (3)",
    answer: "PTV",
    wordplay: "Abbreviation: Planning Target Volume — 'planned' hints at planning",
    length: "(3)",
    difficulty: 3,
  },
  {
    id: "crypt-141",
    clue: "Scattered coherently — this lord's effect keeps wavelength constant (8)",
    answer: "RAYLEIGH",
    wordplay: "Double definition: Rayleigh scattering (coherent, no energy change) — Lord Rayleigh",
    length: "(8)",
    difficulty: 3,
  },
  {
    id: "crypt-142",
    clue: "Fluorescent screen converts X-rays — sounds like it could intensify (12)",
    answer: "FLUOROSCOPY",
    wordplay: "Charade: FLUORO (fluorescent) + SCOPY (viewing) = real-time X-ray imaging",
    length: "(11)",
    difficulty: 3,
  },
  {
    id: "crypt-143",
    clue: "Counting device clicks with each detection — named after a German (6)",
    answer: "GEIGER",
    wordplay: "Double definition: Geiger counter/tube and Hans Geiger who invented it",
    length: "(6)",
    difficulty: 3,
  },
  {
    id: "crypt-144",
    clue: "Electron equilibrium at depth — confused builder up (7)",
    answer: "BUILDUP",
    wordplay: "Anagram: 'builder up' confused — BUILD + UP = electronic buildup region in dose curves",
    length: "(7)",
    difficulty: 3,
  },
  {
    id: "crypt-145",
    clue: "Output factor relates machine setting to delivered amount — sounds like it could put you out (6)",
    answer: "OUTPUT",
    wordplay: "Double definition: output factor in linac dosimetry and output as in production/result",
    length: "(6)",
    difficulty: 3,
  },
  {
    id: "crypt-146",
    clue: "Scattered proton creates this heavier particle — confused neutron (7)",
    answer: "NEUTRON",
    wordplay: "Anagram: 'neutron' — self-referential anagram indicator 'confused/scattered'",
    length: "(7)",
    difficulty: 3,
  },
  {
    id: "crypt-147",
    clue: "Absorbed fraction determines internal dose — AF holds the energy inside (8)",
    answer: "ABSORBED",
    wordplay: "Charade: ABSORB (take in) + ED (editor) = ABSORBED fraction for internal dosimetry",
    length: "(8)",
    difficulty: 3,
  },
  {
    id: "crypt-148",
    clue: "Secondary barrier protects from scattered radiation — sounds like it could be second-hand (9)",
    answer: "SECONDARY",
    wordplay: "Double definition: secondary radiation barrier and secondary/second-hand",
    length: "(9)",
    difficulty: 3,
  },
  {
    id: "crypt-149",
    clue: "Depth of maximum dose — confused max held deep (4)",
    answer: "DMAX",
    wordplay: "Abbreviation: D-max = depth of maximum dose — D (depth) + MAX (maximum)",
    length: "(4)",
    difficulty: 3,
  },
  {
    id: "crypt-150",
    clue: "Percentage depth dose falls with distance — century drops deep (3)",
    answer: "PDD",
    wordplay: "Abbreviation: Percentage Depth Dose — P (percentage) + D (depth) + D (dose)",
    length: "(3)",
    difficulty: 3,
  },
];

export function getRandomClues(count: number, difficulty?: 1 | 2 | 3): CrypticClue[] {
  let pool = [...CRYPTIC_CLUES];
  if (difficulty) pool = pool.filter(c => c.difficulty === difficulty);
  // Shuffle using Fisher-Yates algorithm
  for (let i = pool.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [pool[i], pool[j]] = [pool[j], pool[i]];
  }
  return pool.slice(0, count);
}
